### PR TITLE
Fix: Expose Adapt variable only when Dev Tools drawer is open (fixes #78)

### LINKED ISSUE #78: Change the way window.Adapt is added
### Subject of the issue
[Dev Tools exposes an `Adapt` variable that references `core/js/adapt`.](https://github.com/cgkineo/adapt-devtools/blob/8225a6f99191644da9e23de10fa71ecf5b47d84b/js/utils.js#L74) This is useful for debugging. However, on several occasions, course bugs were not found until final release to the client where Dev Tools is disabled. This obviously makes us look bad to the client.

Ideally, when QA does their final check of the final release, they would look for any errors in the web developer console. Also, in an ideal world, developers would remember to always import the Adapt variable. However, this doesn't always happen in reality.

I would like to see a configuration option to disable the exposed `Adapt` variable.

### Steps to reproduce
1. In a plugin, reference `Adapt` _without_ first importing it with `import Adapt from 'core/js/adapt';`

```
const ariaLabels = Adapt.course.get('_globals')._accessibility._ariaLabels;
```
2. Enable Dev Tools and test the course.
3. Disable Dev Tools and test the course.

### Expected behaviour
No console errors.

### Actual behaviour
Console errors during step 3.

```
ReferenceError: Adapt is not defined
```

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #78 

### Fix
* Exposes the Adapt variable only when the Dev Tools drawer is open
* Adds this as a new "dev tip" in the drawer
* Adjust styling in drawer to reduce vertical space and add formatting to keyboard commands
* _README.md_ - Remove required framework version and update text about `Adapt` variable.
* Removed some deprecated references in _js/adapt-devtools.js_

### Testing
1. Open the browser console
2. Type in `Adapt` into the console
3. Open the Dev Tools drawer
4. Type in `Adapt` into the console

### Expected results
`Adapt` will only be defined when the Dev Tools drawer is open. Otherwise, you will see something like `Uncaught ReferenceError: Adapt is not defined`.

### CODE REVIEW

**Review by guywillis — APPROVED** [review]
👀

**Review by oliverfoster — APPROVED** [review]

File: js/utils.js [hunk 1]
```diff
@@ -24,6 +25,18 @@ function onKeypress(e) {
   console.log(model.attributes);
 }
 
+function onDrawerOpened() {
+  if (drawer?._drawerView?._customView?.get(0).className !== 'devtools') return;
+
+  // Useful for command-line debugging
```
Comment (oliverfoster) [inline js/utils.js:31]:
```suggestion
  // Useful for browser console debugging
```

File: js/utils.js [hunk 2]
```diff
@@ -70,8 +83,10 @@ Adapt.once('adapt:initialize devtools:enable', () => {
   $(window).on('keypress', onKeypress);
   $(window).on('mousedown', onMouseDown);
   $(window).on('mouseup', onMouseUp);
-  // useful for command-line debugging
-  if (!window.Adapt) window.Adapt = Adapt;
+  Adapt.listenTo(Adapt, {
+    'drawer:opened': onDrawerOpened,
+    'drawer:closed': onDrawerClosed
+  });
```
Comment (oliverfoster) [inline js/utils.js:89]:
```suggestion
  Adapt.on({
    'drawer:opened': onDrawerOpened,
    'drawer:closed': onDrawerClosed
  });
```

**Comment by chris-steele** [comment]
Is it possible to have this variable when devtools is _enabled_, not just when the drawer is open? It'd be more useful to have the `Adapt` reference in the console _and_ be able to interact with the course.

**Comment by oliverfoster** [comment]
What about having it added when the dev tools is opened for the first time and not removed thereafter? The trouble of having it enabled as a global variable whilst booting up Adapt would be best mitigated by adding the variable as late a possible and preferably not at all without intent.

**Comment by swashbuck** [comment]
> @swashbuck is it possible to have this variable when devtools is _enabled_, not just when the drawer is open?

@chris-steele This would not solve our original issue when devtools is enabled until we disable it immediately before packaging it up for release. QA would be less likely to catch any errors caused by the Adapt variable being global. In an ideal world, QA would do one final check with devtools disabled before releasing, but that rarely happens.

> What about having it added when the dev tools is opened for the first time and not removing it thereafter?

@oliverfoster I think this would be fine compromise.

**Comment by swashbuck** [comment]
@oliverfoster @chris-steele Let me know if you are fine with the changes in [eef26dc](https://github.com/cgkineo/adapt-devtools/pull/82/commits/eef26dcf15d3d73ef7fe072ae9b3016a61bfde62).

**Review by chris-steele — APPROVED** [review]
